### ISSUE TITLE
Suggested extension / improvement

### ISSUE THREAD

**Issue by firthmj** [GlitchedPolygons/l8w8jwt#15]
How easy would it be to change the library to have versions of the encode and decode functions where the payload JSON was provided / returned just as the JSON text?

There are other good JSON generation / parsing libraries available, and some people may wish to use them to generate or process the payload, rather than the built in claim processing.

**Comment by GlitchedPolygons** [comment]
That's understandable.

I'm unsure whether that would maybe bloat this library's lightweightedness or not. But it's obviously a valid point.

It shouldn't be too hard to make some sort of `l8w8jwt_decode_raw()` function or something like that, that would do exactly the same things as the current decode function except just returning the raw jwt string from the payload.

Claims deserializing starts here at [Line 561](https://github.com/GlitchedPolygons/l8w8jwt/blob/master/src/decode.c#L561) - encoding would occur likewise just by passing the payload's JSON string in as parameter: users would need to **absolutely** ensure themselves manually that the json is actually json and valid, otherwise the JWT would be non-standard.

**Comment by GlitchedPolygons** [comment]
@firthmj Hi again, I hope you had a lovely, ehh, 3 years? ;D

Sorry for the insane delay.

Maybe you don't even remember this, but I never forgot about it. It was always kind of in the back of my head as an unclosed to-do item. I finally found some time to give due love to my FOSS libs on GH. 

I have updated l8w8jwt's dependencies and addressed some of the other issues/feature requests that users reported, including this one. There are now two more decode functions that allow decoding and validating without the l8w8jwt claims struct (it just writes the payload JSON out into a `char*`, exactly as you suggested above :) 

Thanks again for the ticket and recommendation.

Check out release 2.3.0 here: 

https://github.com/GlitchedPolygons/l8w8jwt/releases/tag/2.3.0

:)

Cheers, and have a wonderful 2024!
