### ISSUE TITLE
How to encode/decode a JWT when the "aud" claim is an array of strings

### ISSUE THREAD

**Issue by valentino-fiorin** [GlitchedPolygons/l8w8jwt#19]
As described in the IETF (see [4.1.3.  "aud" (Audience) Claim](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3)):

> The "aud" (audience) claim identifies the recipients that the JWT is intended for. [...]
> In the general case, the "aud" value is an array of case-sensitive strings, each containing a StringOrURI value.

The `l8w8jwt_encoding_params` exposes the `aud` member, which well suits the special case when the JWT has one single audience. However, l8w8jwt still allows encoding a JWT with an array of strings in the "aud" claim by specifying this claim as `additional_payload_claims`. With this workaround, the `l8w8jwt_encode` successfully encodes the token, and the result is a JWT with the expected array of strings in the "aud" claim. 

But, the request to `l8w8jwt_decode` a JWT built in this way will fail with error code `L8W8JWT_DECODE_FAILED_INVALID_TOKEN_FORMAT`. 

What is the correct way to decode such a token?

**Comment by GlitchedPolygons** [comment]
Hi there, thanks for pointing this out! 

Yep, l8w8jwt indeed does not yet support >1 aud claim value (or, rather, its json parser is not consumed in a way fit enough to accept both arrays of audience as well as single values).

I'd have to allocate some time to address this issue; I always only have 1 aud field in my use cases, that's why I didn't notice this. 

Would you have an idea or suggestion on how to implement this into l8w8jwt in an extremely lightweight and minimalistic way? Feel free to submit a PR if you speedy-need this fixed :)

**Comment by firthmj** [comment]
This is the same problem that I had as issue #16. Would there be any chance of getting my suggested change there adopted?

**Comment by GlitchedPolygons** [comment]
Done :)

https://github.com/GlitchedPolygons/l8w8jwt/releases/tag/2.3.0
