### ISSUE TITLE
Are there any plans to update the submodules, especially mbedtls 

### ISSUE THREAD

**Issue by micwinxx** [GlitchedPolygons/l8w8jwt#35]
Currently, the current submodule based version for the latest l8w8jwt 2.1.8 release of mbedtls is 3.1.0. Are there any plans to update to a newer version (3.4.1 current newest release)?

There might be some bugs that have been fixed, e.g., https://www.cve.org/CVERecord?id=CVE-2022-46393.

**Comment by GlitchedPolygons** [comment]
@micwinxx Hi there :)

Yup, will update it as soon as I can. I lack the time right now, but it'll happen this year for sure!

If you need it really fast, you can attempt to fork, analyze, upgrade and open a PR :)

**Comment by micwinxx** [comment]
I ran into some troubles when building with newer mbedtls versions. 

For the current 3.4.1 release there is a compiler warning on a x86_64 Centos 7.9 system with a gcc 4.8.5. The problem is that the cmake files contain `-Wmissing-declarations -Wmissing-prototypes` which is does not work (has been addressed in later gcc I believe, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54113 and https://lists.gnu.org/archive/html/bug-gnulib/2012-08/msg00038.html) and that the ${CMAKE_C_FLAGS} is also evaluated before this warning such that you cannot override them (which makes it a regression in mbedtls). Removing the specific warning flags makes it compile.

The same mbedtls version on an arm64 system with Centos7.9 does not work because it needs at least a gcc 6. I did not resolve this a have not tested further.

I did not test the compiled libraries.

So with such an upgrade some compatibility is lost. 

I may come back to this after switching to newer OS (Centos7.9 runs out of maintenance support on 2024-06-30) and compiler but I cannot guarantee to find time.

**Comment by GlitchedPolygons** [comment]
@micwinxx Finally found some free time for this. I upgraded the underlying MbedTLS version to v3.4.1 and bumped the version number for l8w8jwt, creating release 2.2.0 because it passed my own acceptance criteria of functioning properly on Windows, Ubuntu, Debian and Mac (Mojave x64). I'll leave this ticket open nonetheless though, since it's not _really_ resolved given the problems you stated under CentOS (there I **really** don't have time currently, I'm sorry).

Take care and have a wonderful autumn season! :)

**Comment by micwinxx** [comment]
Sorry for getting back to you that late.

Thank you so much for updating the third party software!
I was wondering if in general you plan to automate that, at least once in a while update the third party software that is pulled in (even though current MbedTLS 3.5.1 seems to have a high vulnerability https://nvd.nist.gov/vuln/detail/CVE-2024-23744).

I think you do not need to worry about the CMAKE flaws of MbedTLS 3.4.1 (which are for example visible on Centos 7.9)   here. 
But, I would highly appreciated if you consider pulling in only third party software and versions which can be build on older (but still supported) stable platforms such as RHEL 8, Rocky 8, Oracle Linux 8 (excluding the older still supported distros with an EOL at most at the end of this year) even though I can understand if you do not have the capacities for this.

**Comment by GlitchedPolygons** [comment]
@micwinxx Hi there, and welcome to 2024 😆

Hope you had a great start! 

No worries, I always try to reply to these GH issues, even if sometimes only [after a very unfriendly delay](https://github.com/GlitchedPolygons/l8w8jwt/issues/28). It's difficult to keep up with these, especially when my time resources are very limited :/

To answer your question: no, I don't think automating this type of thing would be a good idea, because then I have no control over _when_ thinks will fuck up (and they will... and knowing my luck they would most **definitively** fuck up when I have the least amount of time and am under high pressure - I think that's some sort of sick programmers variant of Murphy's law, shit I don't know 😂)

But I will try to update these more often, when I know it's stable and safe to do so :)

It's true, I haven't been giving enough love to my FOSS stuff on GH, I hope I'll have time to do so soon. 

I'll look at the other issues here too and push out a new build soon. Take care and have a nice rest of the week! :)

**Comment by micwinxx** [comment]
Thank you, I hope you also had a great start in 2024. 

(For automation there would be some automated testing needed and so yes I agree and I know the programmers variant for Murphy's law as well.)

Thank you again, take care!

**Comment by GlitchedPolygons** [comment]
@micwinxx I have updated l8w8jwt's dependencies and addressed some of the other issues/feature requests that users reported. Check out release 2.3.0 here: 

https://github.com/GlitchedPolygons/l8w8jwt/releases/tag/2.3.0

:)

Cheers
