### ISSUE TITLE
L8W9JWT_NULL_ARG being returned in when using the example code in documentation

### ISSUE THREAD

**Issue by rsarpal** [GlitchedPolygons/l8w8jwt#6]
Hi,

I have built a dll and I am trying to test it with the Example code "Encoding and signing a token" which is given in the Documentation here. The printf is returning r=100 L8W9JWT_NULL_ARG

What could be the reason for this?

Br,

**Comment by GlitchedPolygons** [comment]
The reason is that one of the params is NULL.

Check out where validation happens:
 https://github.com/GlitchedPolygons/l8w8jwt/blob/5ebe3aec5a4af87322020f7dba541b0b4ba50e4a/src/encode.c#L537

**Comment by rsarpal** [comment]
Yes I have seen that validation,

Could you pls also tell me that does the library support nested claims json as below? If so which type in which variable in struct l8w8jwt_encoding_params this can be passed? Would it be *additional_payload_claims of type l8w8jwt_claim?  How can the nested key, values can be used?

"claims": {
    "Z": {
      "**acr**": {
        "**values**": [
          "**somevalue**"
        ],
        "essential": true
      },
      "A": {
        "value": "somevalue",
        "essential": true
      }
    },
    "B": {
      "BA": {
        "value": "somevalue",
        "essential": true
      }
    }
  }

**Comment by GlitchedPolygons** [comment]
No, nested claims are not supported

**Comment by rsarpal** [comment]
Oh is it ! Could you point me to some other C library which supports nested claims as well?

**Comment by GlitchedPolygons** [comment]
Hm, I don't know if the others listed on jwt.io support nested claims. But I do remember reading somewhere that it is discouraged (and I personally don't use them either because it just doesn't look as nice as a flat layout of claim key-value pairs).

Tokens should contain authorization means, not actual request data: that belongs to e.g. the POST request body/etc...

I'll close this issue for now, thanks for your comments :)
