### ISSUE TITLE
[BUG] Problem in parsing arrays

### ISSUE THREAD

**Issue by michieletto** [GlitchedPolygons/l8w8jwt#7]
**Issue**
The library is not parsing correctly JWT containing array fields.
Every element is considered as key + value. 
Arrays cannot fit into this definition, since they are a set of values.

**To Reproduce**
1. I just used an example (HS256) and changed the token value:

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2MDg3MzM3MzAsImV4cCI6MTY0MDI2OTczMCwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJNYW5hZ2VyMiIsIk1hbmFnZXIzIl19.YXjaonWZU3BBFIVHBhiETRgu9RJZq4NKCP31n0ZMpxY

representing the payload:

{
    "iss": "Online JWT Builder",
    "iat": 1608733730,
    "exp": 1640269730,
    "aud": "www.example.com",
    "sub": "jrocket@example.com",
    "GivenName": "Johnny",
    "Surname": "Rocket",
    "Email": "jrocket@example.com",
    "Role": [
        "Manager",
        "Manager2",
        "Manager3"
    ]
}

2. When executing l8w8jwt_parse_claims, the array is  divided in key + value so that
"Manager" is a key, 
"Manager2" is a value, 
"Manager3" is a key, 
and the output is L8W8JWT_DECODE_FAILED_INVALID_TOKEN_FORMAT [line 128] since there is no value to associate to the last key.
3. In general the same behavior is present each time the variable r computed at line 106 is even.

**Expected behavior**
All the elements of the array should be considered as values of their key, or at least the format should be correctly recognized by the parser.

**Comment by GlitchedPolygons** [comment]
Yup, that's intentional. I did explicitly not implement support for nested JSON tokens, arrays, etc... as it is kind of controversial and mostly (this is the main reason) because I didn't need that additional complexity for my own project. 
It's time consuming, error-prone and by some people even considered bad to not keep your JWT payload's hierarchy flat and key-value only. These are means of authorization, not DTOs ;)

Currently, I don't have time to look into this, I'm sorry. But if you really need it, you can feel free to fork it and open a PR, by all means :)

All the best, and merry Christmas!

**Comment by michieletto** [comment]
Thanks, I will think about creating a PR.
In any case, if possible I suggest to clearly state this intentional limitation in your README.md.

Thanks.
All the best and have a nice Christmas.
